# -*- mode: makefile; indent-tabs-mode: t -*-
# vi: set noet ci pi sts=0 sw=8 ts=8 :
#
# Copyright 2026 Steffen Persvold
# SPDX-License-Identifier: Apache-2.0

PROJECT_ROOT	:= $(shell git rev-parse --show-toplevel)

include sim.mk
